const CATEGORY_KEYWORDS = {
  "Produce": ["avocado", "banana", "apple", "orange", "mango", "peach", "berries", "strawberr", "blueberr", "raspberr", "lemon", "lime", "cucumber", "carrot", "celery", "onion", "garlic", "ginger", "spinach", "basil", "cilantro", "dill", "parsley", "rosemary", "thyme", "tomato", "pepper", "broccoli", "zucchini", "asparagus", "cabbage", "lettuce", "romaine", "potato", "sweet potato", "mushroom", "kale", "green onion", "scallion"],
  "Protein": ["chicken", "turkey", "beef", "steak", "salmon", "shrimp", "egg", "tofu", "lentil", "chickpea", "black bean", "white bean"],
  "Dairy": ["yogurt", "cheese", "cream cheese", "mozzarella", "feta", "cheddar", "parmesan", "milk", "cream", "butter", "sour cream", "cottage cheese"],
  "Pantry": ["olive oil", "sesame oil", "soy sauce", "teriyaki", "peanut butter", "almond butter", "tahini", "honey", "maple syrup", "vinegar", "balsamic", "mustard", "pesto", "hummus", "tomato sauce", "coconut milk", "broth", "stock", "nori"],
  "Grains & Bread": ["rice", "quinoa", "farro", "oat", "pasta", "noodle", "bread", "sourdough", "tortilla", "wrap", "naan", "flour", "granola", "crouton", "breadcrumb"],
  "Nuts & Seeds": ["walnut", "almond", "peanut", "pine nut", "chia", "flax", "hemp", "sesame", "pumpkin seed", "coconut flake"],
  "Spices": ["cumin", "paprika", "turmeric", "curry", "garam masala", "chili", "cinnamon", "cardamom", "italian seasoning", "everything", "tajin", "pepper flake", "vanilla"],
};

const CATEGORY_ORDER = ["Produce", "Protein", "Dairy", "Grains & Bread", "Pantry", "Nuts & Seeds", "Spices", "Other"];

const MEAL_TYPE_LABELS = {
  breakfast: "Breakfast",
  lunch: "Lunch",
  dinner: "Dinner",
  snack: "Snack",
};

/**
 * Classify an ingredient string into a grocery category
 */
export function categorizeIngredient(ingredient) {
  const lower = ingredient.toLowerCase();
  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    if (keywords.some(keyword => lower.includes(keyword))) return category;
  }
  return "Other";
}

/**
 * Build a categorized grocery list from active meals
 */
export function buildGroceryList(meals) {
  const allItems = [];
  for (const [type, meal] of Object.entries(meals)) {
    if (!meal) continue;
    meal.ingredients.forEach(ingredient => {
      allItems.push({
        text: ingredient,
        from: MEAL_TYPE_LABELS[type],
        category: categorizeIngredient(ingredient),
      });
    });
  }

  const grouped = {};
  allItems.forEach(item => {
    if (!grouped[item.category]) grouped[item.category] = [];
    grouped[item.category].push(item);
  });

  const sorted = {};
  CATEGORY_ORDER.forEach(category => {
    if (grouped[category]) sorted[category] = grouped[category];
  });
  return sorted;
}

/**
 * Format grocery list as plain text for copying/sharing
 */
export function groceryToText(groceryList, week) {
  let text = `🛒 MAMA MEAL PLAN — WEEK ${week} GROCERY LIST\n${"─".repeat(40)}\n\n`;
  for (const [category, items] of Object.entries(groceryList)) {
    text += `${category.toUpperCase()}\n`;
    items.forEach(item => {
      text += `  ☐ ${item.text}  (${item.from})\n`;
    });
    text += "\n";
  }
  text += `───────────────────────────────────────\nGenerated by Mama Meal Plan`;
  return text;
}
